{"componentChunkName":"component---src-templates-blog-post-js","path":"/2021-12-05-python-notebook-nbextensions-issue/","result":{"data":{"site":{"siteMetadata":{"title":"Howard's Note","disqusShortname":""}},"markdownRemark":{"id":"c6a4b190-5606-51d5-9a60-a96e870759a9","html":"<h2>問題</h2>\n<p>安裝<code class=\"language-text\">jupyter note extentions</code>，重新啟動終端機後 ，打開 <code class=\"language-text\">jupyter notebook</code> 不會出現 nb-extentions 頁簽。</p>\n<p>web consle 出現以下 error 訊息：</p>\n<div class=\"gatsby-highlight\" data-language=\"bash\"><pre class=\"language-bash\"><code class=\"language-bash\">Failed to load extension:\nArray <span class=\"token punctuation\">[</span> <span class=\"token string\">\"nbextensions/nbextensions_configurator/tree_tab/main\"</span> <span class=\"token punctuation\">]</span>\n Error: Script error <span class=\"token keyword\">for</span> <span class=\"token string\">\"nbextensions/nbextensions_configurator/tree_tab/main\"</span></code></pre></div>\n<p><span\n      class=\"gatsby-resp-image-wrapper\"\n      style=\"position: relative; display: block; margin-left: auto; margin-right: auto; max-width: 630px; \"\n    >\n      <a\n    class=\"gatsby-resp-image-link\"\n    href=\"/static/487718130cc42365b45d88a324d46427/3dde1/error.png\"\n    style=\"display: block\"\n    target=\"_blank\"\n    rel=\"noopener\"\n  >\n    <span\n    class=\"gatsby-resp-image-background-image\"\n    style=\"padding-bottom: 8.227848101265824%; position: relative; bottom: 0; left: 0; background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAACCAIAAADXZGvcAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAa0lEQVQI10XISw6DMAwAUe5/vS4aqSmhTWU7tsEhQanCoh9WSG8xmsGcNxfQQ7xGunhyTx1R7zAH+gfcUB88hyQTN9IOfEjaUTrJAH6U10LRFsw5rZZKlpq5rLJlrgLlOFyN617ad3t/Tu0H4A5uVIOYHlYAAAAASUVORK5CYII='); background-size: cover; display: block;\"\n  ></span>\n  <img\n        class=\"gatsby-resp-image-image\"\n        alt=\"error message\"\n        title=\"error message\"\n        src=\"/static/487718130cc42365b45d88a324d46427/f058b/error.png\"\n        srcset=\"/static/487718130cc42365b45d88a324d46427/c26ae/error.png 158w,\n/static/487718130cc42365b45d88a324d46427/6bdcf/error.png 315w,\n/static/487718130cc42365b45d88a324d46427/f058b/error.png 630w,\n/static/487718130cc42365b45d88a324d46427/40601/error.png 945w,\n/static/487718130cc42365b45d88a324d46427/3dde1/error.png 1018w\"\n        sizes=\"(max-width: 630px) 100vw, 630px\"\n        style=\"width:100%;height:100%;margin:0;vertical-align:middle;position:absolute;top:0;left:0;\"\n        loading=\"lazy\"\n      />\n  </a>\n    </span></p>\n<h2>Root cause</h2>\n<p>會發生這個問題的原因是因為，jupyter notebook 的作用域／環境變數設定，跟 nb-extentions 的不一致而產生。</p>\n<h2>Reproduce</h2>\n<ol>\n<li>使用venv進入某一個python 虛擬環境內。</li>\n<li>安裝<code class=\"language-text\">jupyter notebook</code></li>\n<li>安裝 nb-extentions。</li>\n<li>關閉終端機，重新開啟。</li>\n<li>直接進入 jupyter notebook。</li>\n</ol>\n<h2>Solution</h2>\n<h3>for now:</h3>\n<p>每一次使用 jupyter notebook 都進入前一次安裝的venv內。</p>\n<h3>better:</h3>\n<p>notebook 的 kernel 和 notebook 本身的安裝是分開來的。</p>\n<p>之後使用全域python重新安裝 notebook，</p>\n<p>並且在venv內設定 ipykernel，將ipykernel 安裝到 user目錄底下。</p>\n<p>ref: <a href=\"https://zhuanlan.zhihu.com/p/33257881?utm_source=pocket_mylist\">https://zhuanlan.zhihu.com/p/33257881?utm_source=pocket_mylist</a></p>","frontmatter":{"title":"jupyter notebook nbextensiions 404 issue.","date":"December 05, 2021","description":null,"tags":["python"],"template":"post"}}},"pageContext":{"slug":"/2021-12-05-python-notebook-nbextensions-issue/","previous":{"node":{"fields":{"slug":"/2021-12-03-python-note/"},"frontmatter":{"date":"03 December, 2021","title":"Python Note","tags":["python"]}}},"next":{"node":{"fields":{"slug":"/2021-12-16-python-data-inspect-note1/"},"frontmatter":{"date":"16 December, 2021","title":"data inspect note","tags":["python","note"]}}}}},"staticQueryHashes":["2841359383","3810545343","916993862"]}